// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvtlksovazqamkpwdpef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2dGxrc292YXpxYW1rcHdkcGVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MDI2MTksImV4cCI6MjA2MDA3ODYxOX0.mxUEApZmdTlgfEATw6P34Jm7M80lurLty9w_MdvHU9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);